package com.example.anan.AAChartCore.AAChartCoreLib.AAChartEnum;

public interface AAChartAnimationType {
    String Linear         = "linear";
    String EaseInQuad     = "easeInQuad";
    String EaseOutQuad    = "easeOutQuad";
    String EaseInOutQuad  = "easeInOutQuad";
    String EaseInCubic    = "easeInCubic";
    String EaseOutCubic   = "easeOutCubic";
    String EaseInOutCubic = "easeInOutCubic";
    String EaseInQuart    = "easeInQuart";
    String EaseOutQuart   = "easeOutQuart";
    String EaseInOutQuart = "easeInOutQuart";
    String EaseInQuint    = "easeInQuint";
    String EaseOutQuint   = "easeOutQuint";
    String EaseInOutQuint = "easeInOutQuint";
    String EaseInSine     = "easeInSine";
    String EaseOutSine    = "easeOutSine";
    String EaseInOutSine  = "easeInOutSine";
    String EaseInExpo     = "easeInExpo";
    String EaseOutExpo    = "easeOutExpo";
    String EaseInOutExpo  = "easeInOutExpo";
    String EaseInCirc     = "easeInCirc";
    String EaseOutCirc    = "easeOutCirc";
    String EaseInOutCirc  = "easeInOutCirc";
    String EaseOutBounce  = "easeOutBounce";
    String EaseInBack     = "easeInBack";
    String EaseOutBack    = "easeOutBack";
    String EaseInOutBack  = "easeInOutBack";
    String Elastic        = "elastic";
    String SwingFromTo    = "swingFromTo";
    String SwingFrom      = "swingFrom";
    String SwingTo        = "swingTo";
    String Bounce         = "bounce";
    String BouncePast     = "bouncePast";
    String EaseFromTo     = "easeFromTo";
    String EaseFrom       = "easeFrom";
    String EaseTo         = "easeTo";
}
